#ifndef EXIT_NO_ERRORS
#define EXIT_NO_ERRORS 0
#define ECHOED 0
#define EXIT_BAD_ARGUMENT_COUNT 1
#define EXIT_BAD_FILE_NAME 2
#define EXIT_BAD_MAGICNUMBER 3
#define EXIT_BAD_COMMENTLINE 4
#define EXIT_BAD_DIMENSIONS 5
#define EXIT_MAXGRAY_VALUE 6
#define EXIT_IMAGE_MALLOC_FAILED 7
#define EXIT_BAD_DATA 8
#define EXIT_OUTPUT_FAILED 9
#define EXIT_MISELLANEOUS 100

#endif