#ifndef MAGIC_NUMBER_RAW
#define MIN_IMAGE_DIMENSION 1
#define MAX_IMAGE_DIMENSION 65535
#define MAX_COMMENT_LINE_LENGTH 256
#define PGM_GRAY_VALUE 255
#define MAGIC_NUMBER_RAW_PGM '5'
#define MAGIC_NUMBER_ASCII_PGM '2'
#endif
